theme: jekyll-theme-midnight
title: "☣️ COVID-19 Bio-Intelligence & Trend Analytics"
description: "Advanced Epidemiological Data Science Framework for Real-Time Caseload Forecasting and Mutation Velocity Mapping."
